make backup script use sh instead of zsh

diff --git a/script/backup b/script/backup
--- a/script/backup
+++ b/script/backup
@@ -1,7 +1,7 @@
-#!/usr/bin/env zsh
-set -Eeuo pipefail
+#!/bin/sh
+set -euo pipefail
 
-trap 'err=$?; echo "Failed to backup database! Status Code: $err"; exit $err' ERR 
+trap 'err=$?; echo "Failed to backup database! Status Code: $err"; exit $err' ERR
 
 db_name='stats.sqlite3'
 db_backup='stats.sqlite3.bak'
